apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kafka
resources:
  - namespace.yaml
  - https://strimzi.io/install/latest?namespace=kafka
  - https://strimzi.io/examples/latest/kafka/kafka-persistent-single.yaml
  - topics.yaml