apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: words
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 2
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: wordcount
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 2
  replicas: 1